package cli

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/nathandelacretaz/dark-research-lab/internal/memory"
	"github.com/nathandelacretaz/dark-research-lab/internal/setup"
	"github.com/nathandelacretaz/dark-research-lab/internal/util"
	"github.com/spf13/cobra"
)

// ========================== improve ==========================

func improveCmd() *cobra.Command {
	var (
		output     string
		maxIters   int
		budget     int
		model      string
		force      bool
		topics     string
		compactPct int
	)

	cmd := &cobra.Command{
		Use:   "improve",
		Short: "Generate improvement loop script",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runImprove(cmd, output, maxIters, budget, model, force, topics, compactPct)
		},
	}

	// init subcommand
	initCmd := &cobra.Command{
		Use:   "init",
		Short: "Create example improvement program",
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "improve"
			if v, _ := cmd.Flags().GetString("dir"); v != "" {
				dir = v
			}
			return createExampleImproveFile(cmd, dir)
		},
	}
	initCmd.Flags().String("dir", "improve", "Directory for improvement programs")
	cmd.AddCommand(initCmd)

	cmd.Flags().StringVarP(&output, "output", "o", "improvement-loop.sh", "Output script path")
	cmd.Flags().IntVar(&maxIters, "max-iters", 5, "Max iterations per topic")
	cmd.Flags().IntVar(&budget, "time-budget", 0, "Total time budget in seconds (0=unlimited)")
	cmd.Flags().StringVar(&model, "model", "claude-opus-4-6[1m]", "Claude model to use")
	cmd.Flags().BoolVarP(&force, "force", "f", false, "Overwrite existing script")
	cmd.Flags().StringVar(&topics, "topics", "", "Comma-separated topic names to run")
	cmd.Flags().IntVar(&compactPct, "compact-pct", 0, "Context auto-compaction threshold % (0=use Claude Code default, suggested: 50)")
	return cmd
}

// runImprove implements the RunE body for the improve command.
func runImprove(cmd *cobra.Command, output string, maxIters, budget int, model string, force bool, topics string, compactPct int) error {
	if compactPct < 0 || compactPct > 100 {
		return fmt.Errorf("--compact-pct must be 0-100, got %d", compactPct)
	}
	if !force {
		if _, err := os.Stat(output); err == nil {
			return fmt.Errorf("file %s already exists (use --force to overwrite)", output)
		}
	}

	topicFilter := ""
	if topics != "" {
		topicFilter = topics
	}

	script := generateImproveScript(maxIters, budget, model, topicFilter, compactPct)

	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}
	if err := os.WriteFile(output, []byte(script), 0755); err != nil {
		return fmt.Errorf("write script: %w", err)
	}

	cmd.Printf("[ok] Generated improvement script: %s\n", output)
	cmd.Println("Run it with: bash " + output)
	return nil
}

func createExampleImproveFile(cmd *cobra.Command, dir string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}

	example := `# Code Quality Improvement

## Goal
Improve code quality by fixing linting issues, adding missing type annotations,
and removing dead code.

## Validation
- All tests pass
- No new linting violations
- Changes are focused and minimal
`
	path := filepath.Join(dir, "code-quality.md")
	if _, err := os.Stat(path); err == nil {
		cmd.Printf("[info] %s already exists\n", path)
		return nil
	}
	if err := os.WriteFile(path, []byte(example), 0644); err != nil {
		return fmt.Errorf("write example: %w", err)
	}
	cmd.Printf("[ok] Created example improvement program: %s\n", path)
	return nil
}

func generateImproveScript(maxIters, timeBudget int, model, topicFilter string, compactPct int) string {
	timestamp := time.Now().Format(time.RFC3339)
	escapedModel := util.ShellEscape(model)
	escapedTopicFilter := util.ShellEscape(topicFilter)

	config := improveScriptConfig(timestamp, maxIters, timeBudget, escapedModel, escapedTopicFilter, compactPct)
	functions := improveScriptFunctions()
	mainLoop := improveScriptMainLoop()

	return config + functions + mainLoop
}

// improveScriptConfig returns the header, config, and mkdir section of the improve script.
func improveScriptConfig(timestamp string, maxIters, timeBudget int, escapedModel, escapedTopicFilter string, compactPct int) string {
	compactLine := ""
	if compactPct > 0 {
		compactLine = fmt.Sprintf("export CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=%d  # Trigger context compaction at %d%% capacity\n", compactPct, compactPct)
	}
	return fmt.Sprintf(`#!/usr/bin/env bash
# Improvement Loop - Generated by: drl improve
# Date: %s
# Iterates over improve/*.md programs to autonomously improve the codebase.
#
# Usage:
#   ./improvement-loop.sh
#   IMPROVE_DRY_RUN=1 ./improvement-loop.sh  # Preview without executing

set -euo pipefail

# Config
MAX_ITERS=%d
TIME_BUDGET=%d
MODEL=%s
TOPIC_FILTER=%s
LOG_DIR="agent_logs"
START_TIME=$(date +%%s)
%s
mkdir -p "$LOG_DIR"

`, timestamp, maxIters, timeBudget, escapedModel, escapedTopicFilter, compactLine)
}

// improveScriptFunctions returns the topic discovery, prompt builder, and marker detection bash functions.
func improveScriptFunctions() string {
	return `# --- Topic Discovery ---
get_topics() {
  local topics=()
  for f in improve/*.md; do
    [ -f "$f" ] || continue
    local name
    name=$(basename "$f" .md)
    if [ -n "$TOPIC_FILTER" ]; then
      echo "$TOPIC_FILTER" | tr ',' '\n' | grep -qx "$name" || continue
    fi
    topics+=("$name")
  done
  printf '%s\n' "${topics[@]}"
}

# --- Prompt Builder ---
build_prompt() {
  local topic="$1"
  local file="improve/${topic}.md"
  echo "You are running in an autonomous improvement loop."
  echo ""
  echo "Read and implement the improvement program in: $file"
  echo ""
  echo "When done, output one of these markers on its own line:"
  echo "  IMPROVED        - Changes were made and tests pass"
  echo "  NO_IMPROVEMENT  - No meaningful improvements found"
  echo "  FAILED          - Could not complete the improvement"
}

# --- Marker Detection ---
detect_marker() {
  local file="$1"
  if grep -q "^IMPROVED$" "$file" 2>/dev/null; then echo "IMPROVED"; return; fi
  if grep -q "^NO_IMPROVEMENT$" "$file" 2>/dev/null; then echo "NO_IMPROVEMENT"; return; fi
  if grep -q "^FAILED$" "$file" 2>/dev/null; then echo "FAILED"; return; fi
  echo "UNKNOWN"
}

`
}

// improveScriptMainLoop returns the main iteration loop of the improve script.
func improveScriptMainLoop() string {
	return improveScriptLoopSetup() + improveScriptInnerLoop() + improveScriptSummary()
}

func improveScriptLoopSetup() string {
	return `# --- Main Loop ---
COMPLETED=0
FAILED_COUNT=0
echo "[improve] Starting improvement loop"

for topic in $(get_topics); do
  echo "[improve] Topic: $topic"
  no_improve_streak=0

  for ((iter=1; iter<=MAX_ITERS; iter++)); do
    # Time budget check
    if [ "$TIME_BUDGET" -gt 0 ]; then
      elapsed=$(( $(date +%s) - START_TIME ))
      if [ "$elapsed" -ge "$TIME_BUDGET" ]; then
        echo "[improve] Time budget exhausted"
        break 2
      fi
    fi

    echo "[improve] $topic iteration $iter/$MAX_ITERS"
    TRACE_FILE="$LOG_DIR/trace_improve_${topic}_$(date +%Y%m%d_%H%M%S).jsonl"
    MACRO_FILE="$LOG_DIR/macro_improve_${topic}_$(date +%Y%m%d_%H%M%S).txt"

    # Create git checkpoint
    git tag "improve/${topic}/iter-${iter}/pre" 2>/dev/null || true

    if [ "${IMPROVE_DRY_RUN:-}" = "1" ]; then
      echo "[improve] DRY RUN: would spawn claude for $topic"
      continue
    fi

    # Spawn Claude session
    PROMPT=$(build_prompt "$topic")
    claude --dangerously-skip-permissions --permission-mode auto --model "$MODEL" --output-format stream-json -p "$PROMPT" > "$TRACE_FILE" 2>/dev/null || true

    # Extract text and detect marker
    if command -v jq >/dev/null 2>&1; then
      jq -r 'select(.type=="assistant") | .message.content[]? | select(.type=="text") | .text' "$TRACE_FILE" > "$MACRO_FILE" 2>/dev/null || true
    fi

    MARKER=$(detect_marker "$MACRO_FILE")
`
}

func improveScriptInnerLoop() string {
	return `    case "$MARKER" in
      IMPROVED)
        echo "[improve] $topic: improved (iteration $iter)"
        git add -A && git commit -m "improve($topic): iteration $iter" 2>/dev/null || true
        COMPLETED=$((COMPLETED + 1))
        no_improve_streak=0
        ;;
      NO_IMPROVEMENT)
        echo "[improve] $topic: no improvement found"
        git stash push -m "drl-improve: rolled back" 2>/dev/null || true
        no_improve_streak=$((no_improve_streak + 1))
        if [ "$no_improve_streak" -ge 2 ]; then
          echo "[improve] $topic: diminishing returns, moving on"
          break
        fi
        ;;
      FAILED|UNKNOWN)
        echo "[improve] $topic: failed"
        git stash push -m "drl-improve: rolled back" 2>/dev/null || true
        FAILED_COUNT=$((FAILED_COUNT + 1))
        break
        ;;
    esac
  done
done
`
}

func improveScriptSummary() string {
	return `
echo ""
echo "[improve] Summary: $COMPLETED improvements, $FAILED_COUNT failures"
`
}

// ========================== loop ==========================

// loopCmdOptions captures all flag values for the loop command.
type loopCmdOptions struct {
	output, model, epics, reviewers, reviewModel string
	maxRetries, reviewEvery, maxReviewCycles     int
	improveMaxIters, improveTimeBudget           int
	compactPct                                   int
	force, reviewBlocking, improve               bool
}

func loopCmd() *cobra.Command {
	var o loopCmdOptions

	cmd := &cobra.Command{
		Use:   "loop",
		Short: "Generate infinity loop script for epic processing",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runLoop(cmd, &o)
		},
	}

	cmd.Flags().StringVarP(&o.output, "output", "o", "infinity-loop.sh", "Output script path")
	cmd.Flags().IntVar(&o.maxRetries, "max-retries", 1, "Max retries per epic on failure")
	cmd.Flags().StringVar(&o.model, "model", "claude-opus-4-6[1m]", "Claude model to use")
	cmd.Flags().BoolVarP(&o.force, "force", "f", false, "Overwrite existing script")
	cmd.Flags().StringVar(&o.epics, "epics", "", "Comma-separated epic IDs to process")
	cmd.Flags().StringVar(&o.reviewers, "reviewers", "", "Comma-separated reviewers (claude-sonnet,claude-opus,gemini,codex)")
	cmd.Flags().IntVar(&o.reviewEvery, "review-every", 0, "Review every N completed epics (0=end-only)")
	cmd.Flags().IntVar(&o.maxReviewCycles, "max-review-cycles", 3, "Max review/fix iterations")
	cmd.Flags().BoolVar(&o.reviewBlocking, "review-blocking", false, "Fail loop if review not approved after max cycles")
	cmd.Flags().StringVar(&o.reviewModel, "review-model", "claude-opus-4-6[1m]", "Model for implementer fix sessions")
	cmd.Flags().BoolVar(&o.improve, "improve", false, "Run improvement phase after all epics complete")
	cmd.Flags().IntVar(&o.improveMaxIters, "improve-max-iters", 5, "Max improvement iterations per topic")
	cmd.Flags().IntVar(&o.improveTimeBudget, "improve-time-budget", 0, "Total improvement time budget in seconds (0=unlimited)")
	cmd.Flags().IntVar(&o.compactPct, "compact-pct", 0, "Context auto-compaction threshold % (0=use Claude Code default, suggested: 50)")
	return cmd
}

func runLoop(cmd *cobra.Command, o *loopCmdOptions) error {
	if o.compactPct < 0 || o.compactPct > 100 {
		return fmt.Errorf("--compact-pct must be 0-100, got %d", o.compactPct)
	}
	output := o.output
	if output == "" {
		output = "infinity-loop.sh"
	}
	if !o.force {
		if _, err := os.Stat(output); err == nil {
			return fmt.Errorf("file %s already exists (use --force to overwrite)", output)
		}
	}

	opts := loopGenerateOptions{maxRetries: o.maxRetries, model: o.model, epics: o.epics, compactPct: o.compactPct}

	if o.reviewers != "" {
		reviewerList := strings.Split(o.reviewers, ",")
		if err := validateReviewers(reviewerList); err != nil {
			return err
		}
		opts.review = &loopReviewOptions{
			reviewers: reviewerList, maxReviewCycles: o.maxReviewCycles,
			reviewBlocking: o.reviewBlocking, reviewModel: o.reviewModel, reviewEvery: o.reviewEvery,
		}
	}
	if o.improve {
		opts.improve = &loopImproveOptions{maxIters: o.improveMaxIters, timeBudget: o.improveTimeBudget}
	}

	script := generateLoopScript(opts)

	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}
	if err := os.WriteFile(output, []byte(script), 0755); err != nil {
		return fmt.Errorf("write script: %w", err)
	}
	cmd.Printf("[ok] Generated infinity loop script: %s\n", output)
	cmd.Println("Run it with: bash " + output)
	return nil
}

// loopGenerateOptions holds all options for generating the loop script.
type loopGenerateOptions struct {
	maxRetries int
	compactPct int
	model      string
	epics      string
	review     *loopReviewOptions
	improve    *loopImproveOptions
}

func generateLoopScript(opts loopGenerateOptions) string {
	escapedModel := util.ShellEscape(opts.model)
	// Replace commas with spaces so bash `for` loop iterates correctly.
	escapedEpicIDs := util.ShellEscape(strings.ReplaceAll(opts.epics, ",", " "))
	bt := "`" // backtick for use in templates

	config := loopScriptConfig(opts.maxRetries, escapedModel, escapedEpicIDs, opts.compactPct)
	crashHandler := loopScriptCrashHandler()
	memorySafety := loopScriptMemorySafety()
	parseJSON := loopScriptParseJSON()
	epicSelector := loopScriptEpicSelector()
	promptBuilder := loopScriptPromptBuilder(bt)

	var reviewSection string
	if opts.review != nil {
		reviewSection = loopScriptReviewConfig(*opts.review) +
			loopScriptReviewerDetection() +
			loopScriptSessionIDManagement() +
			loopScriptReviewPrompt() +
			loopScriptSpawnReviewers() +
			loopScriptImplementerPhase() +
			loopScriptReviewLoop()
	}

	helpers := loopScriptHelpers()
	preLoop := loopScriptPreLoop()
	whileHeader := loopScriptWhileHeader()
	epicProcessing := loopScriptEpicProcessing()

	// Build review trigger fragments (empty strings if no reviewers).
	var triggerInit, triggerPeriodic, triggerFinal string
	if opts.review != nil {
		triggerInit, triggerPeriodic, triggerFinal = loopScriptReviewTriggers(opts.review.reviewEvery)
	}

	// Inject triggers at the correct positions:
	// - triggerInit: BEFORE the while loop (after pre-loop vars)
	// - triggerPeriodic: INSIDE the success branch (via epicResult parameter)
	// - triggerFinal: AFTER the done (before summary/push)
	epicResult := loopScriptEpicResult(triggerPeriodic)
	postLoop := loopScriptPostLoop(triggerFinal, opts.improve != nil)

	mainLoop := helpers + preLoop + triggerInit + whileHeader +
		epicProcessing + epicResult + postLoop

	script := config + crashHandler + memorySafety + parseJSON +
		epicSelector + promptBuilder + reviewSection + mainLoop

	if opts.improve != nil {
		script += loopScriptImprovePhase(*opts.improve)
	}

	return script
}

// loopScriptConfig returns the header, config vars, helpers, and mkdir section.
func loopScriptConfig(maxRetries int, escapedModel, escapedEpicIDs string, compactPct int) string {
	timestamp := time.Now().Format(time.RFC3339)

	var b strings.Builder
	fmt.Fprintf(&b, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&b, "# Infinity Loop - Generated by: drl loop\n")
	fmt.Fprintf(&b, "# Date: %s\n", timestamp)
	fmt.Fprintf(&b, "# Autonomously processes beads epics via Claude Code sessions.\n")
	fmt.Fprintf(&b, "#\n# Usage:\n#   ./infinity-loop.sh\n")
	fmt.Fprintf(&b, "#   LOOP_DRY_RUN=1 ./infinity-loop.sh  # Preview without executing\n\n")
	fmt.Fprintf(&b, "set -euo pipefail\n\n")

	// Config variables
	fmt.Fprintf(&b, "# Config\n")
	fmt.Fprintf(&b, "MAX_RETRIES=%d\n", maxRetries)
	fmt.Fprintf(&b, "MODEL=%s\n", escapedModel)
	fmt.Fprintf(&b, "EPIC_IDS=%s\n", escapedEpicIDs)
	fmt.Fprintf(&b, "LOG_DIR=\"agent_logs\"\n")
	fmt.Fprintf(&b, "MIN_FREE_MEMORY_PCT=${MIN_FREE_MEMORY_PCT:-20}  # Stop loop if free memory drops below this %%\n")
	fmt.Fprintf(&b, "WATCHDOG_THRESHOLD=${WATCHDOG_THRESHOLD:-15}     # Kill session if free memory drops below this %%\n")
	fmt.Fprintf(&b, "WATCHDOG_INTERVAL=${WATCHDOG_INTERVAL:-30}       # Seconds between watchdog checks\n")
	fmt.Fprintf(&b, "SESSION_STALE_TIMEOUT=${SESSION_STALE_TIMEOUT:-1800}  # Kill session if no output for this many seconds\n")
	if compactPct > 0 {
		fmt.Fprintf(&b, "export CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=%d  # Trigger context compaction at %d%% capacity\n", compactPct, compactPct)
	}
	fmt.Fprintf(&b, "\n")

	// Helpers
	fmt.Fprintf(&b, "# Helpers\n")
	fmt.Fprintf(&b, "timestamp() { date '+%%Y-%%m-%%d_%%H-%%M-%%S'; }\n")
	fmt.Fprintf(&b, "# log() writes to stderr so it never corrupts command-substitution captures\n")
	fmt.Fprintf(&b, "log() { echo \"[$(timestamp)] $*\" >&2; }\n")
	fmt.Fprintf(&b, "die() { log \"FATAL: $*\"; exit 1; }\n\n")

	// CLI prerequisites
	fmt.Fprintf(&b, "command -v claude >/dev/null || die \"claude CLI required\"\n")
	fmt.Fprintf(&b, "command -v bd >/dev/null || die \"bd (beads) CLI required\"\n\n")

	// JSON parser detection
	fmt.Fprintf(&b, "# Detect JSON parser: prefer jq, fall back to python3\n")
	fmt.Fprintf(&b, "HAS_JQ=false\n")
	fmt.Fprintf(&b, "command -v jq >/dev/null 2>&1 && HAS_JQ=true\n")
	fmt.Fprintf(&b, "if [ \"$HAS_JQ\" = false ]; then\n")
	fmt.Fprintf(&b, "  command -v python3 >/dev/null 2>&1 || die \"jq or python3 required for JSON parsing\"\n")
	fmt.Fprintf(&b, "fi\n\n")

	fmt.Fprintf(&b, "mkdir -p \"$LOG_DIR\"\n\n")
	return b.String()
}

// loopScriptCrashHandler returns the EXIT trap that logs crash details to the status file.
func loopScriptCrashHandler() string {
	return `# Crash handler: log WHY we died and update status file
_loop_cleanup() {
  local exit_code=$?
  stop_memory_watchdog 2>/dev/null || true
  stop_stale_watchdog 2>/dev/null || true
  if [ $exit_code -ne 0 ]; then
    log "CRASH: Script exited with code $exit_code at line ${BASH_LINENO[0]:-unknown}"
    echo "{\"status\":\"crashed\",\"exit_code\":$exit_code,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"line\":\"${BASH_LINENO[0]:-unknown}\"}" > "${LOG_DIR:-.}/.loop-status.json" 2>/dev/null || true
  fi
}
trap _loop_cleanup EXIT

`
}

// loopScriptMemorySafety returns the 4-layer memory defense: orphan cleanup,
// memory gate, memory watchdog, and stale output watchdog.
func loopScriptMemorySafety() string { //nolint:funlen // bash template string
	return `# --- Memory Safety (4-Layer Defense) ---

# cleanup_orphans() - Kill leftover test/build processes from THIS repo between sessions
# Scoped to current working directory to avoid killing unrelated processes
cleanup_orphans() {
  local killed=0
  local repo_dir
  repo_dir=$(pwd)
  for pid in $(pgrep -f "vitest|node.*\.test\.|go\.test|pytest|cargo\.test" 2>/dev/null || true); do
    local proc_cwd=""
    if [ "$(uname)" = "Darwin" ]; then
      proc_cwd=$(lsof -p "$pid" -Fn 2>/dev/null | grep '^ncwd' | sed 's/^n//' || true)
    else
      proc_cwd=$(readlink "/proc/$pid/cwd" 2>/dev/null || true)
    fi
    # Only kill if the process cwd is exactly this repo or a subdirectory
    case "$proc_cwd" in
      "$repo_dir"|"$repo_dir"/*) kill "$pid" 2>/dev/null && killed=$((killed + 1)) ;;
    esac
  done
  if [ "$killed" -gt 0 ]; then
    log "Cleaned up $killed orphan test processes"
    sleep 2  # Let OS reclaim memory
  fi
}

# get_memory_pct() - Return current free memory percentage on stdout (empty on failure)
get_memory_pct() {
  if [ "$(uname)" = "Darwin" ]; then
    memory_pressure 2>/dev/null | awk -F: '/free percentage/ {gsub(/%| /,"",$2); print $2}'
  else
    local mem_total mem_available
    mem_total=$(awk '/MemTotal/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)
    mem_available=$(awk '/MemAvailable/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)
    if [ "$mem_total" -gt 0 ]; then
      echo $(( mem_available * 100 / mem_total ))
    fi
  fi
}

# check_memory() - Abort if system free memory is too low
check_memory() {
  local free_pct
  free_pct=$(get_memory_pct)
  if [ -z "$free_pct" ]; then
    return 0  # Can't measure, assume OK
  fi
  if [ "$free_pct" -lt "$MIN_FREE_MEMORY_PCT" ]; then
    log "WARN: System memory ${free_pct}% free (minimum: ${MIN_FREE_MEMORY_PCT}%)"
    return 1
  fi
  log "Memory OK: ${free_pct}% free"
  return 0
}

# start_memory_watchdog() - Background monitor that kills target PID on memory pressure
# Args: $1=PID to kill, $2=log file for memory stats
# Sets: WATCHDOG_PID (global)
WATCHDOG_PID=""

start_memory_watchdog() {
  local target_pid="$1"
  local mem_log="$2"
  (
    while kill -0 "$target_pid" 2>/dev/null; do
      local pct
      pct=$(get_memory_pct)
      if [ -n "$pct" ]; then
        echo "[$(date '+%Y-%m-%d_%H-%M-%S')] memory_free=${pct}%" >> "$mem_log"
        if [ "$pct" -lt "$WATCHDOG_THRESHOLD" ]; then
          echo "[$(date '+%Y-%m-%d_%H-%M-%S')] WATCHDOG: memory ${pct}% < ${WATCHDOG_THRESHOLD}%, killing PID $target_pid" >> "$mem_log"
          kill -TERM -- -"$target_pid" 2>/dev/null || kill "$target_pid" 2>/dev/null || true
          exit 0
        fi
      fi
      sleep "$WATCHDOG_INTERVAL"
    done
  ) &
  WATCHDOG_PID=$!
}

stop_memory_watchdog() {
  if [ -n "$WATCHDOG_PID" ]; then
    kill "$WATCHDOG_PID" 2>/dev/null || true
    wait "$WATCHDOG_PID" 2>/dev/null || true
    WATCHDOG_PID=""
  fi
}

# start_stale_watchdog() - Background monitor that kills target PID on output inactivity
# Args: $1=PID to kill, $2=trace file to monitor, $3=log file for events
# Sets: STALE_WATCHDOG_PID (global)
STALE_WATCHDOG_PID=""

start_stale_watchdog() {
  local target_pid="$1"
  local trace_file="$2"
  local log_file="$3"
  (
    local last_size=0
    local stale_secs=0
    while kill -0 "$target_pid" 2>/dev/null; do
      sleep "$WATCHDOG_INTERVAL"
      local cur_size=0
      [ -f "$trace_file" ] && cur_size=$(wc -c < "$trace_file" 2>/dev/null || echo 0)
      if [ "$cur_size" -eq "$last_size" ] && [ "$last_size" -gt 0 ]; then
        stale_secs=$((stale_secs + WATCHDOG_INTERVAL))
        if [ "$stale_secs" -ge "$SESSION_STALE_TIMEOUT" ]; then
          echo "[$(date '+%Y-%m-%d_%H-%M-%S')] STALE_WATCHDOG: no output for ${stale_secs}s, killing PID $target_pid" >> "$log_file"
          kill -TERM -- -"$target_pid" 2>/dev/null || kill "$target_pid" 2>/dev/null || true
          exit 0
        fi
      else
        stale_secs=0
      fi
      last_size=$cur_size
    done
  ) &
  STALE_WATCHDOG_PID=$!
}

stop_stale_watchdog() {
  if [ -n "$STALE_WATCHDOG_PID" ]; then
    kill "$STALE_WATCHDOG_PID" 2>/dev/null || true
    wait "$STALE_WATCHDOG_PID" 2>/dev/null || true
    STALE_WATCHDOG_PID=""
  fi
}

`
}

// loopScriptParseJSON returns the parse_json function with jq/python3 fallback.
func loopScriptParseJSON() string {
	return `# --- JSON Parsing ---
# parse_json() - extract a value from JSON stdin
# Uses jq (primary) with python3 fallback
# Auto-unwraps single-element arrays (bd show --json returns [...])
# Usage: echo '[{"status":"open"}]' | parse_json '.status'
parse_json() {
  local filter="$1"
  if [ "$HAS_JQ" = true ]; then
    jq -r "if type == \"array\" then .[0] else . end | $filter"
  else
    python3 -c "
import sys, json
data = json.load(sys.stdin)
if isinstance(data, list):
    data = data[0] if data else {}
f = sys.argv[1].strip('.')
parts = [p for p in f.split('.') if p]
v = data
try:
    for p in parts:
        v = v[p]
except (KeyError, IndexError, TypeError):
    v = None
print('' if v is None else v)
" "$filter"
  fi
}

`
}

// loopScriptEpicSelector returns the check_deps_closed and get_next_epic bash functions.
func loopScriptEpicSelector() string { //nolint:funlen // bash template string
	return `# --- Epic Selector ---

# check_deps_closed() - Verify all depends_on for an epic are closed
# Returns 0 if all deps closed (or no deps), 1 if any dep is open
check_deps_closed() {
  local epic_id="$1"
  local deps_json
  deps_json=$(bd show "$epic_id" --json 2>/dev/null || echo "")
  if [ -z "$deps_json" ]; then
    return 0
  fi
  local blocking_dep
  if [ "$HAS_JQ" = true ]; then
    blocking_dep=$(echo "$deps_json" | jq -r '
      if type == "array" then .[0] else . end |
      (.depends_on // .dependencies // []) |
      map(select(.status != "closed")) |
      .[0].id // empty
    ' 2>/dev/null || echo "")
  else
    blocking_dep=$(echo "$deps_json" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if isinstance(data, list):
    data = data[0] if data else {}
deps = data.get('depends_on', data.get('dependencies', []))
for d in deps:
    s = d.get('status', 'open') if isinstance(d, dict) else 'open'
    if s != 'closed':
        print(d.get('id', d) if isinstance(d, dict) else d)
        break
" 2>/dev/null || echo "")
  fi
  if [ -n "$blocking_dep" ]; then
    log "Skip $epic_id: blocked by dependency $blocking_dep (not closed)"
    return 1
  fi
  return 0
}

get_next_epic() {
  if [ -n "$EPIC_IDS" ]; then
    for epic_id in $EPIC_IDS; do
      case " $PROCESSED " in (*" $epic_id "*) continue ;; esac
      local status
      status=$(bd show "$epic_id" --json 2>/dev/null | parse_json '.status' 2>/dev/null || echo "")
      if [ "$status" = "open" ]; then
        check_deps_closed "$epic_id" || continue
        echo "$epic_id"
        return 0
      fi
    done
    return 1
  else
    local epic_id
    if [ "$HAS_JQ" = true ]; then
      epic_id=$(bd list --type=epic --ready --json --limit=10 2>/dev/null | jq -r '.[].id' 2>/dev/null | while read -r id; do
        case " $PROCESSED " in (*" $id "*) continue ;; esac
        check_deps_closed "$id" || continue
        echo "$id"
        break
      done)
    else
      local candidates
      candidates=$(bd list --type=epic --ready --json --limit=10 2>/dev/null | python3 -c "
import sys, json
processed = set(sys.argv[1].split())
items = json.load(sys.stdin)
for item in items:
    if item['id'] not in processed:
        print(item['id'])" "$PROCESSED" 2>/dev/null || echo "")
      for cid in $candidates; do
        check_deps_closed "$cid" || continue
        epic_id="$cid"
        break
      done
    fi
    if [ -z "$epic_id" ]; then
      return 1
    fi
    echo "$epic_id"
    return 0
  fi
}

`
}

// loopScriptPromptBuilder returns the build_prompt bash function.
func loopScriptPromptBuilder(bt string) string { //nolint:funlen // bash template string
	var b strings.Builder
	fmt.Fprintf(&b, "# --- Prompt Builder ---\n")
	fmt.Fprintf(&b, "build_prompt() {\n")
	fmt.Fprintf(&b, "  local epic_id=\"$1\"\n")
	fmt.Fprintf(&b, "  cat <<'PROMPT_HEADER'\n")
	fmt.Fprintf(&b, "You are running in an autonomous infinity loop. Your task is to fully implement a beads epic.\n\n")
	fmt.Fprintf(&b, "## Step 1: Load context\n")
	fmt.Fprintf(&b, "Run these commands to prime your session:\n")
	fmt.Fprintf(&b, "PROMPT_HEADER\n")
	fmt.Fprintf(&b, "  cat <<PROMPT_BODY\n")
	fmt.Fprintf(&b, "\\%s\\%s\\%sbash\n", bt, bt, bt)
	fmt.Fprintf(&b, "npx drl load-session\n")
	fmt.Fprintf(&b, "bd show $epic_id\n")
	fmt.Fprintf(&b, "\\%s\\%s\\%s\n\n", bt, bt, bt)
	fmt.Fprintf(&b, "Read the epic details carefully. Understand scope, acceptance criteria, and sub-tasks.\n\n")
	fmt.Fprintf(&b, "## Step 2: Execute the workflow\n")
	fmt.Fprintf(&b, "Run the full compound workflow for this epic, starting from the plan phase\n")
	fmt.Fprintf(&b, "(spec-dev is already done -- the epic exists):\n\n")
	fmt.Fprintf(&b, "/compound:cook-it from plan -- Epic: $epic_id\n\n")
	fmt.Fprintf(&b, "Work through all phases: plan, work, review, compound.\n\n")
	fmt.Fprintf(&b, "## Step 3: On completion\n")
	fmt.Fprintf(&b, "When all work is done and tests pass:\n")
	fmt.Fprintf(&b, "1. Close the epic: \\%sbd close $epic_id\\%s\n", bt, bt)
	fmt.Fprintf(&b, "2. Commit and push all changes\n")
	fmt.Fprintf(&b, "3. Output this exact marker on its own line:\n\n")
	fmt.Fprintf(&b, "EPIC_COMPLETE\n\n")
	fmt.Fprintf(&b, "## Step 4: On failure\n")
	fmt.Fprintf(&b, "If you cannot complete the epic after reasonable effort:\n")
	fmt.Fprintf(&b, "1. Add a note: \\%sbd update $epic_id --notes \"Loop failed: <reason>\"\\%s\n", bt, bt)
	fmt.Fprintf(&b, "2. Output this exact marker on its own line:\n\n")
	fmt.Fprintf(&b, "EPIC_FAILED\n\n")
	fmt.Fprintf(&b, "## Step 5: On human required\n")
	fmt.Fprintf(&b, "If you hit a blocker that REQUIRES human action (account creation, API keys,\n")
	fmt.Fprintf(&b, "external service setup, design decisions you cannot make, etc.):\n")
	fmt.Fprintf(&b, "1. Add a note: \\%sbd update $epic_id --notes \"Human required: <reason>\"\\%s\n", bt, bt)
	fmt.Fprintf(&b, "2. Output this exact marker followed by a short reason on the SAME line:\n\n")
	fmt.Fprintf(&b, "HUMAN_REQUIRED: <reason>\n\n")
	fmt.Fprintf(&b, "Example: HUMAN_REQUIRED: Need AWS credentials configured in .env\n\n")
	fmt.Fprintf(&b, "## Memory Safety Rules\n")
	fmt.Fprintf(&b, "- For Go work, use \\%sgo test ./...\\%s in the go/ directory.\n", bt, bt)
	fmt.Fprintf(&b, "- NEVER run embedding tests unless the epic modifies embedding code.\n")
	fmt.Fprintf(&b, "- Between test runs, wait for all child processes to exit before starting another.\n\n")
	fmt.Fprintf(&b, "## Rules\n")
	fmt.Fprintf(&b, "- Do NOT ask questions -- there is no human. Make reasonable decisions.\n")
	fmt.Fprintf(&b, "- Do NOT stop early -- complete the full workflow.\n")
	fmt.Fprintf(&b, "- If tests fail, fix them. Retry up to 3 times before declaring failure.\n")
	fmt.Fprintf(&b, "- Use HUMAN_REQUIRED only for true blockers that no amount of retrying can solve.\n")
	fmt.Fprintf(&b, "- Commit incrementally as you make progress.\n")
	fmt.Fprintf(&b, "PROMPT_BODY\n")
	fmt.Fprintf(&b, "}\n\n")
	return b.String()
}

func loopScriptHelpers() string { //nolint:funlen // bash template string
	return `# --- Text Extractor ---
# extract_text() - Extract assistant text from stream-json events on stdin
# Claude Code stream-json: {"type":"assistant","message":{"content":[{"type":"text","text":"..."}]}}
extract_text() {
  if [ "$HAS_JQ" = true ]; then
    jq -j --unbuffered '
      select(.type == "assistant") |
      .message.content[]? |
      select(.type == "text") |
      .text // empty
    ' 2>/dev/null || { echo "WARN: extract_text parser failed" >&2; }
  else
    python3 -c "
import sys, json
for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    try:
        obj = json.loads(line)
        if obj.get('type') == 'assistant':
            for block in obj.get('message', {}).get('content', []):
                if block.get('type') == 'text':
                    text = block.get('text', '')
                    if text:
                        print(text, end='', flush=True)
    except (json.JSONDecodeError, KeyError, TypeError):
        pass
" 2>/dev/null || { echo "WARN: extract_text parser failed" >&2; }
  fi
}

# --- Marker Detection ---
# detect_marker() - Check for completion markers in log and trace
# Primary: macro log (anchored patterns). Fallback: trace JSONL (unanchored).
# Returns: "complete", "failed", "human:<reason>", or "none"
detect_marker() {
  local logfile="$1" tracefile="$2"

  # Primary: check extracted text with anchored patterns
  if [ -s "$logfile" ]; then
    if grep -q "^EPIC_COMPLETE$" "$logfile"; then
      echo "complete"; return 0
    elif grep -q "^HUMAN_REQUIRED:" "$logfile"; then
      local reason
      reason=$(grep "^HUMAN_REQUIRED:" "$logfile" | head -1 | sed 's/^HUMAN_REQUIRED: *//')
      echo "human:$reason"; return 0
    elif grep -q "^EPIC_FAILED$" "$logfile"; then
      echo "failed"; return 0
    fi
  fi

  # Fallback: check raw trace JSONL (unanchored -- markers are inside JSON strings)
  if [ -s "$tracefile" ]; then
    if grep -q "EPIC_COMPLETE" "$tracefile"; then
      echo "complete"; return 0
    elif grep -q "HUMAN_REQUIRED:" "$tracefile"; then
      echo "human:detected in trace"; return 0
    elif grep -q "EPIC_FAILED" "$tracefile"; then
      echo "failed"; return 0
    fi
  fi

  echo "none"
}

# --- Observability ---
STATUS_FILE="$LOG_DIR/.loop-status.json"
EXEC_LOG="$LOG_DIR/loop-execution.jsonl"

write_status() {
  local status="$1"
  local epic_id="${2:-}"
  local attempt="${3:-0}"
  if [ "$status" = "idle" ]; then
    echo "{\"status\":\"idle\",\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" > "$STATUS_FILE"
  else
    echo "{\"epic_id\":\"$epic_id\",\"attempt\":$attempt,\"started_at\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"status\":\"$status\"}" > "$STATUS_FILE"
  fi
}

log_result() {
  local epic_id="$1" result="$2" attempts="$3" duration="$4"
  echo "{\"epic_id\":\"$epic_id\",\"result\":\"$result\",\"attempts\":$attempts,\"duration_s\":$duration,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}" >> "$EXEC_LOG"
}

`
}

// loopScriptPreLoop returns the variable initialization before the while loop.
func loopScriptPreLoop() string {
	return `# --- Main Loop ---
COMPLETED=0
FAILED_COUNT=0
SKIPPED=0
PROCESSED=""
LOOP_START=$(date +%s)

log "=========================================="
log "Infinity loop starting"
log "=========================================="
log "Config: max_retries=$MAX_RETRIES model=$MODEL"
[ -n "$EPIC_IDS" ] && log "Targeting epics: $EPIC_IDS" || log "Targeting: all ready epics"

`
}

// loopScriptWhileHeader returns the while-loop opening and per-epic setup.
func loopScriptWhileHeader() string {
	return `while true; do
  # Memory safety: clean up orphans and check memory before starting next epic
  cleanup_orphans
  if ! check_memory; then
    log "FATAL: Memory pressure too high, stopping loop to prevent system freeze"
    log "  Hint: set MIN_FREE_MEMORY_PCT (current: ${MIN_FREE_MEMORY_PCT}%) or kill background processes"
    FAILED_COUNT=$((FAILED_COUNT + 1))
    break
  fi

  EPIC_ID=$(get_next_epic) || break

  log "=========================================="
  log "Processing epic: $EPIC_ID"
  log "=========================================="
  EPIC_START=$(date +%s)

  ATTEMPT=0
  SUCCESS=false

  write_status "running" "$EPIC_ID" 1

`
}

func loopScriptEpicProcessing() string {
	return loopScriptAttemptSetup() + loopScriptAttemptCases()
}

func loopScriptAttemptSetup() string { //nolint:funlen // bash template string
	return `  while [ $ATTEMPT -le $MAX_RETRIES ]; do
    ATTEMPT=$((ATTEMPT + 1))
    TS=$(timestamp)
    LOGFILE="$LOG_DIR/loop_$EPIC_ID-$TS.log"
    TRACEFILE="$LOG_DIR/trace_$EPIC_ID-$TS.jsonl"

    write_status "running" "$EPIC_ID" "$ATTEMPT"

    # Update .latest symlink for drl watch (before claude invocation so watch can discover it)
    ln -sf "$(basename "$TRACEFILE")" "$LOG_DIR/.latest"

    log "Attempt $ATTEMPT/$((MAX_RETRIES + 1)) for $EPIC_ID (log: $LOGFILE)"

    # Clean stale phase state from previous epic or architect session
    drl phase-check clean 2>/dev/null || true

    if [ -n "${LOOP_DRY_RUN:-}" ]; then
      log "[DRY RUN] Would run claude session for $EPIC_ID"
      SUCCESS=true
      break
    fi

    PROMPT=$(build_prompt "$EPIC_ID")

    # Two-scope logging: stream-json to trace JSONL, extracted text to macro log
    # Run in background subshell so we can track PID for the memory watchdog
    MEM_LOG="$LOG_DIR/memory_${EPIC_ID}-${TS}.log"
    (
      claude --dangerously-skip-permissions \
             --permission-mode auto \
             --model "$MODEL" \
             --output-format stream-json \
             --verbose \
             -p "$PROMPT" \
             2>"$LOGFILE.stderr" | tee "$TRACEFILE" | extract_text > "$LOGFILE"
    ) &
    CLAUDE_PGID=$!
    start_memory_watchdog "$CLAUDE_PGID" "$MEM_LOG"
    start_stale_watchdog "$CLAUDE_PGID" "$TRACEFILE" "$MEM_LOG"
    wait "$CLAUDE_PGID" 2>/dev/null || true
    stop_stale_watchdog
    stop_memory_watchdog

    # Detect if watchdog killed the session
    if [ -f "$MEM_LOG" ] && grep -q "STALE_WATCHDOG:" "$MEM_LOG" 2>/dev/null; then
      log "WARN: Session killed by stale output watchdog (see $MEM_LOG)"
      cleanup_orphans
    elif [ -f "$MEM_LOG" ] && grep -q "WATCHDOG:" "$MEM_LOG" 2>/dev/null; then
      log "WARN: Session killed by memory watchdog (see $MEM_LOG)"
      cleanup_orphans
    fi

    # Append stderr to macro log
    [ -f "$LOGFILE.stderr" ] && cat "$LOGFILE.stderr" >> "$LOGFILE" && rm -f "$LOGFILE.stderr"

    # Health check: warn if macro log extraction failed
    if [ -s "$TRACEFILE" ] && [ ! -s "$LOGFILE" ]; then
      log "WARN: Macro log is empty but trace has content (extract_text may have failed)"
    fi

    MARKER=$(detect_marker "$LOGFILE" "$TRACEFILE")
`
}

func loopScriptAttemptCases() string {
	return `    case "$MARKER" in
      (complete)
        log "Epic $EPIC_ID completed successfully"
        SUCCESS=true
        break
        ;;
      (human:*)
        REASON="${MARKER#human:}"
        log "Epic $EPIC_ID needs human action: $REASON"
        bd update "$EPIC_ID" --notes "Human required: $REASON" 2>/dev/null || true
        SUCCESS=skip
        break
        ;;
      (failed)
        log "Epic $EPIC_ID reported failure (attempt $ATTEMPT)"
        ;;
      (*)
        log "Epic $EPIC_ID session ended without marker (attempt $ATTEMPT)"
        ;;
    esac

    if [ $ATTEMPT -le $MAX_RETRIES ]; then
      log "Retrying $EPIC_ID..."
      cleanup_orphans
      sleep 5
    fi
  done

`
}

// loopScriptEpicResult returns the per-epic result handling inside the while loop.
// The periodicTrigger is injected into the success branch.
func loopScriptEpicResult(periodicTrigger string) string { //nolint:funlen // bash template string
	return `  EPIC_DURATION=$(( $(date +%s) - EPIC_START ))

  if [ "$SUCCESS" = true ]; then
    if [ -z "${LOOP_DRY_RUN:-}" ]; then
    # Verify working tree is clean after epic completion
    if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
      log "WARN: Working tree dirty after epic completion, auto-committing"
      git add -A && git commit -m "chore: auto-commit uncommitted changes from $EPIC_ID" 2>/dev/null || true
    fi
    COMPLETED=$((COMPLETED + 1))
    log_result "$EPIC_ID" "complete" "$ATTEMPT" "$EPIC_DURATION"
    log "Epic $EPIC_ID done. Completed so far: $COMPLETED"
` + periodicTrigger + `
    fi
  elif [ "$SUCCESS" = skip ]; then
    SKIPPED=$((SKIPPED + 1))
    log_result "$EPIC_ID" "skipped" "$ATTEMPT" "$EPIC_DURATION"
    log "Epic $EPIC_ID skipped (human required). Continuing."
  else
    FAILED_COUNT=$((FAILED_COUNT + 1))
    log_result "$EPIC_ID" "failed" "$ATTEMPT" "$EPIC_DURATION"
    log "Epic $EPIC_ID failed after $((MAX_RETRIES + 1)) attempts. Stopping loop."
    PROCESSED="$PROCESSED $EPIC_ID"
    break
  fi

  PROCESSED="$PROCESSED $EPIC_ID"
done

`
}

// loopScriptPostLoop returns the post-loop section: final review trigger, summary, git push.
// When hasImprove is true, the exit line is omitted (the improve phase footer handles exit).
func loopScriptPostLoop(finalTrigger string, hasImprove bool) string {
	exit := `# Zero-work detection: exit 2 if no epics completed and none failed
if [ "$COMPLETED" -eq 0 ] && [ "$FAILED_COUNT" -eq 0 ]; then
  log "WARN: Zero epics completed -- all may be blocked or skipped"
  exit 2
fi
[ $FAILED_COUNT -eq 0 ] && exit 0 || exit 1
`
	if hasImprove {
		exit = "" // improve phase footer provides its own exit
	}

	return finalTrigger + `
TOTAL_DURATION=$(( $(date +%s) - LOOP_START ))

if [ -z "${LOOP_DRY_RUN:-}" ]; then
echo "{\"type\":\"summary\",\"completed\":$COMPLETED,\"failed\":$FAILED_COUNT,\"skipped\":$SKIPPED,\"total_duration_s\":$TOTAL_DURATION}" >> "$EXEC_LOG"
write_status "idle"

# Push to remote if available
if git remote get-url origin >/dev/null 2>&1; then
  log "Pushing to remote..."
  git push 2>&1 || log "WARN: git push failed (check SSH/auth)"
fi
fi

log "=========================================="
log "Loop finished"
log "  Completed: $COMPLETED"
log "  Failed:    $FAILED_COUNT"
log "  Skipped:   $SKIPPED"
log "  Duration:  ${TOTAL_DURATION}s ($(( TOTAL_DURATION / 60 ))m)"
log "  Processed: $PROCESSED"
log "=========================================="
` + exit
}

// ========================== watch ==========================

func watchCmd() *cobra.Command {
	var (
		epicID  string
		follow  bool
		improve bool
		logDir  string
	)

	cmd := &cobra.Command{
		Use:   "watch",
		Short: "Tail and pretty-print live trace from infinity loop sessions",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runWatch(cmd, epicID, follow, improve, logDir)
		},
	}

	cmd.Flags().StringVar(&epicID, "epic", "", "Watch a specific epic trace")
	cmd.Flags().BoolVar(&follow, "follow", false, "Follow the file (not yet implemented, reads once)")
	cmd.Flags().BoolVar(&improve, "improve", false, "Watch improvement loop traces")
	cmd.Flags().StringVar(&logDir, "log-dir", "", "Log directory (default: agent_logs/)")
	// Support --no-follow
	cmd.Flags().Lookup("follow").NoOptDefVal = "true"
	return cmd
}

// runWatch implements the RunE body for the watch command.
func runWatch(cmd *cobra.Command, epicID string, follow, improve bool, logDir string) error {
	if logDir == "" {
		repoRoot := util.GetRepoRoot()
		logDir = filepath.Join(repoRoot, "agent_logs")
	}

	traceFile := resolveTraceFile(cmd, epicID, improve, logDir)
	if traceFile == "" {
		return nil
	}

	cmd.Printf("[info] Watching: %s\n", traceFile)

	if follow {
		return tailFollow(cmd, traceFile)
	}
	return readAndFormat(cmd, traceFile)
}

// resolveTraceFile finds the appropriate trace file based on flags.
// Returns empty string and prints a message if no trace is found.
func resolveTraceFile(cmd *cobra.Command, epicID string, improve bool, logDir string) string {
	if epicID != "" {
		traceFile := findTraceForEpic(logDir, epicID)
		if traceFile == "" {
			cmd.Printf("[error] No trace file found for epic: %s\n", epicID)
		}
		return traceFile
	}
	if improve {
		traceFile := findLatestTrace(logDir, "trace_improve_")
		if traceFile == "" {
			cmd.Println("[info] No improvement trace found.")
		}
		return traceFile
	}
	traceFile := findLatestTrace(logDir, "trace_")
	if traceFile == "" {
		cmd.Println("[info] No active trace found. Run `drl loop` first.")
	}
	return traceFile
}

func findLatestTrace(logDir, prefix string) string {
	if _, err := os.Stat(logDir); os.IsNotExist(err) {
		return ""
	}

	// Check .latest symlink first
	latestPath := filepath.Join(logDir, ".latest")
	if target, err := os.Readlink(latestPath); err == nil {
		resolved := filepath.Join(logDir, target)
		if _, err := os.Stat(resolved); err == nil && strings.HasPrefix(target, prefix) {
			return resolved
		}
	}

	// Fallback: find most recent file
	entries, err := os.ReadDir(logDir)
	if err != nil {
		return ""
	}

	var matches []string
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), prefix) && strings.HasSuffix(e.Name(), ".jsonl") {
			matches = append(matches, e.Name())
		}
	}
	sort.Sort(sort.Reverse(sort.StringSlice(matches)))
	if len(matches) > 0 {
		return filepath.Join(logDir, matches[0])
	}
	return ""
}

func findTraceForEpic(logDir, epicID string) string {
	// Reject path separators to prevent directory traversal
	if strings.ContainsAny(epicID, "/\\") {
		return ""
	}
	prefix := fmt.Sprintf("trace_%s-", epicID)
	return findLatestTrace(logDir, prefix)
}

// streamEvent represents a parsed stream-json event.
type streamEvent struct {
	Type         string `json:"type"`
	Timestamp    string `json:"timestamp,omitempty"`
	ContentBlock *struct {
		Type string `json:"type"`
		Name string `json:"name,omitempty"`
	} `json:"content_block,omitempty"`
	Delta *struct {
		Type string `json:"type"`
		Text string `json:"text,omitempty"`
	} `json:"delta,omitempty"`
	Message *struct {
		Usage *struct {
			InputTokens  int `json:"input_tokens,omitempty"`
			OutputTokens int `json:"output_tokens,omitempty"`
		} `json:"usage,omitempty"`
	} `json:"message,omitempty"`
	Usage *struct {
		OutputTokens int `json:"output_tokens,omitempty"`
	} `json:"usage,omitempty"`
	Result string `json:"result,omitempty"`
}

func formatStreamEvent(event streamEvent) string {
	ts := formatEventTime(event.Timestamp)

	switch event.Type {
	case "content_block_start":
		return formatContentBlockStart(ts, event)
	case "content_block_delta":
		return formatContentBlockDelta(ts, event)
	case "message_delta":
		return formatMessageDelta(ts, event)
	case "message_start":
		return formatMessageStart(ts, event)
	case "result":
		return formatResultEvent(ts, event)
	}
	return ""
}

// formatContentBlockStart formats a content_block_start event.
func formatContentBlockStart(ts string, event streamEvent) string {
	if event.ContentBlock == nil {
		return ""
	}
	if event.ContentBlock.Type == "tool_use" {
		return fmt.Sprintf("%s TOOL    %s", ts, event.ContentBlock.Name)
	}
	if event.ContentBlock.Type == "thinking" {
		return fmt.Sprintf("%s THINK   thinking...", ts)
	}
	return ""
}

// formatContentBlockDelta formats a content_block_delta event.
func formatContentBlockDelta(ts string, event streamEvent) string {
	if event.Delta == nil || event.Delta.Type != "text_delta" {
		return ""
	}
	text := strings.ReplaceAll(event.Delta.Text, "\n", " ")
	if len(text) > 60 {
		text = text[:57] + "..."
	}
	return fmt.Sprintf("%s TEXT    %s", ts, text)
}

// formatMessageDelta formats a message_delta event.
func formatMessageDelta(ts string, event streamEvent) string {
	if event.Usage != nil && event.Usage.OutputTokens > 0 {
		return fmt.Sprintf("%s TOKENS  %d out (final)", ts, event.Usage.OutputTokens)
	}
	return ""
}

// formatMessageStart formats a message_start event.
func formatMessageStart(ts string, event streamEvent) string {
	if event.Message != nil && event.Message.Usage != nil {
		return fmt.Sprintf("%s TOKENS  %d in / %d out", ts,
			event.Message.Usage.InputTokens, event.Message.Usage.OutputTokens)
	}
	return ""
}

// formatResultEvent formats a result event, extracting any known markers.
func formatResultEvent(ts string, event streamEvent) string {
	if event.Result == "" {
		return ""
	}
	markers := []string{
		"EPIC_COMPLETE", "EPIC_FAILED", "HUMAN_REQUIRED",
		"NO_IMPROVEMENT", "IMPROVED", "FAILED",
	}
	for _, m := range markers {
		if !strings.Contains(event.Result, m) {
			continue
		}
		line := extractMarkerLine(event.Result, m)
		if len(line) > 120 {
			line = line[:117] + "..."
		}
		return fmt.Sprintf("%s MARKER  %s", ts, line)
	}
	return ""
}

// extractMarkerLine finds the line containing the marker in the result text.
func extractMarkerLine(result, marker string) string {
	for _, l := range strings.Split(result, "\n") {
		if strings.Contains(l, marker) {
			return l
		}
	}
	return result
}

func formatEventTime(timestamp string) string {
	if timestamp == "" {
		return time.Now().Format("15:04:05")
	}
	t, err := time.Parse(time.RFC3339, timestamp)
	if err != nil {
		return time.Now().Format("15:04:05")
	}
	return t.Format("15:04:05")
}

func readAndFormat(cmd *cobra.Command, path string) error {
	f, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open trace: %w", err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		var event streamEvent
		if err := json.Unmarshal([]byte(line), &event); err != nil {
			continue
		}
		formatted := formatStreamEvent(event)
		if formatted != "" {
			cmd.Println(formatted)
		}
	}
	return scanner.Err()
}

func tailFollow(cmd *cobra.Command, path string) error {
	// For simplicity, just read and format (follow mode would need goroutines + fsnotify)
	// In practice, the bash script's `tail -f` is more reliable
	return readAndFormat(cmd, path)
}

// ========================== audit ==========================

type auditFinding struct {
	File     string `json:"file,omitempty"`
	Issue    string `json:"issue"`
	Severity string `json:"severity"` // "error", "warning", "info"
	Source   string `json:"source"`   // "rule", "pattern", "lesson"
}

type auditReport struct {
	Findings []auditFinding `json:"findings"`
	Summary  struct {
		Errors   int `json:"errors"`
		Warnings int `json:"warnings"`
		Infos    int `json:"infos"`
	} `json:"summary"`
}

func auditCmd() *cobra.Command {
	var (
		repoRoot string
		jsonOut  bool
	)

	cmd := &cobra.Command{
		Use:   "audit",
		Short: "Run audit checks against the codebase",
		RunE: func(cmd *cobra.Command, args []string) error {
			if repoRoot == "" {
				repoRoot = util.GetRepoRoot()
			}

			report := runAuditChecks(repoRoot)

			if jsonOut {
				data, err := json.MarshalIndent(report, "", "  ")
				if err != nil {
					return fmt.Errorf("marshal audit report: %w", err)
				}
				cmd.Println(string(data))
				return nil
			}

			for _, f := range report.Findings {
				label := strings.ToUpper(f.Severity)
				filePart := ""
				if f.File != "" {
					filePart = " " + f.File
				}
				cmd.Printf("%s [%s]%s -- %s\n", label, f.Source, filePart, f.Issue)
			}

			cmd.Println()
			cmd.Printf("Audit: %d finding(s), %d error(s), %d warning(s), %d info(s)\n",
				len(report.Findings), report.Summary.Errors, report.Summary.Warnings, report.Summary.Infos)
			return nil
		},
	}

	cmd.Flags().StringVar(&repoRoot, "repo-root", "", "Repository root")
	cmd.Flags().BoolVar(&jsonOut, "json", false, "output as JSON")
	return cmd
}

func runAuditChecks(repoRoot string) auditReport {
	var findings []auditFinding

	findings = append(findings, checkClaudeDir(repoRoot)...)
	findings = append(findings, checkLessonsIndex(repoRoot)...)
	findings = append(findings, checkHooksConfigured(repoRoot)...)
	findings = append(findings, checkGitignore(repoRoot)...)
	findings = append(findings, checkLessonHealth(repoRoot)...)

	return buildAuditReport(findings)
}

// checkClaudeDir checks whether the .claude/ directory exists.
func checkClaudeDir(repoRoot string) []auditFinding {
	if _, err := os.Stat(filepath.Join(repoRoot, ".claude")); os.IsNotExist(err) {
		return []auditFinding{{
			Issue:    ".claude/ directory missing — run drl init",
			Severity: "error",
			Source:   "rule",
		}}
	}
	return nil
}

// checkLessonsIndex checks whether the lessons index file exists.
func checkLessonsIndex(repoRoot string) []auditFinding {
	indexPath := filepath.Join(repoRoot, ".claude", "lessons", "index.jsonl")
	if _, err := os.Stat(indexPath); os.IsNotExist(err) {
		return []auditFinding{{
			Issue:    "Lessons index missing — run drl init",
			Severity: "error",
			Source:   "rule",
		}}
	}
	return nil
}

// checkHooksConfigured checks whether Claude Code hooks are fully configured.
func checkHooksConfigured(repoRoot string) []auditFinding {
	settingsPath := filepath.Join(repoRoot, ".claude", "settings.json")
	settings, err := setup.ReadClaudeSettings(settingsPath)
	if err != nil || !setup.HasAllHooks(settings) {
		return []auditFinding{{
			Issue:    "Claude Code hooks not fully configured — run drl setup claude",
			Severity: "warning",
			Source:   "rule",
		}}
	}
	return nil
}

// checkGitignore checks whether .claude/.gitignore exists.
func checkGitignore(repoRoot string) []auditFinding {
	gitignorePath := filepath.Join(repoRoot, ".claude", ".gitignore")
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		return []auditFinding{{
			Issue:    ".claude/.gitignore missing — run drl init",
			Severity: "warning",
			Source:   "rule",
		}}
	}
	return nil
}

// checkLessonHealth checks lesson age and count for potential issues.
func checkLessonHealth(repoRoot string) []auditFinding {
	result, err := memory.ReadItems(repoRoot)
	if err != nil {
		return nil
	}

	var findings []auditFinding
	oldCount := countOldLessons(result.Items)
	if oldCount > 0 {
		findings = append(findings, auditFinding{
			Issue:    fmt.Sprintf("%d lesson(s) are over 90 days old — review for validity", oldCount),
			Severity: "info",
			Source:   "lesson",
		})
	}
	if len(result.Items) > 50 {
		findings = append(findings, auditFinding{
			Issue:    fmt.Sprintf("%d lessons in index — consider running drl compact", len(result.Items)),
			Severity: "info",
			Source:   "lesson",
		})
	}
	return findings
}

// buildAuditReport constructs an auditReport from a slice of findings.
func buildAuditReport(findings []auditFinding) auditReport {
	report := auditReport{Findings: findings}
	if report.Findings == nil {
		report.Findings = []auditFinding{}
	}
	for _, f := range findings {
		switch f.Severity {
		case "error":
			report.Summary.Errors++
		case "warning":
			report.Summary.Warnings++
		case "info":
			report.Summary.Infos++
		}
	}
	return report
}

func registerScriptCommands(rootCmd *cobra.Command) {
	rootCmd.AddCommand(improveCmd())
	rootCmd.AddCommand(loopCmd())
	rootCmd.AddCommand(polishCmd())
	rootCmd.AddCommand(watchCmd())
	rootCmd.AddCommand(auditCmd())
}
